config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  devise_for :users, except: [:index]

  resources :users, only: [:show]

  resources :regions, only: [:show]

  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :region
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :dogs

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @regions = Region.all
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def show
    @region = Region.find(params[:id])
    @dogs = Dog.where(region_id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit

  end

  def update
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
  <div class="top-bar-left">
    <strong><%= link_to "NS4AR", root_path, id: "link" %></strong>
  </div>

  <section class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a href="#">About</a>
        <ul class="menu">
          <li><a href="#">Who We Are</a></li>
          <li><a href="#">Aussie Facts</a></li>
          <li><a href="#">Donate</a></li>
          <li><a href="#">Volunteer</a></li>
          <li><a href="#">Resources</a></li>
        </ul>
      </li>
      <li>
        <a href="#">Adoptable Dogs</a>
        <ul class="menu">
          <% if @regions %>
            <% @regions.each do |region| %>
              <li><%= link_to region.name, region_path(region) %></li>
            <% end %>
          <% end %>
          <li><a href="#">Happy Endings</a></li>
        </ul>
      </li>
        <% if current_user %>
          <li>  signed in as <%= current_user.first_name %></li> |
          <li><%= link_to "View Profile", user_path(current_user), id: "link" %> </li>|
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, id: "link" %></li>
          <% if current_user.admin == true %>
            <li>| <%= link_to "Admin", admin_users_path, id: "link" %></li>
          <% end %>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path, id: "link" %></li>
          <li><%= link_to 'Sign In', new_user_session_path, id: "link" %></li>
        <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "NS4AR" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |key, value| %>
      <div class="flash text-center flash-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/regions/show.html.erb
<div class="callout">
  <% if @dogs %>
    <% @dogs.each do |dog| %>
      <div><%= dog.name %> (NS<%= dog.ns_id %>)</div>
      <div><%= dog.description %></div>
      <div>Located in: <%= dog.location %></div>
      <div></div>
    <% end %>
  <% end %>
</div>